export const fixtures = {
  auth: {
    email: 'admin@xpory.local',
    password: 'Xpory#123',
    token: 'test-token',
  },
  inventory: {
    summary: {
      stacks: 2,
      instances: 1,
      endpoints: 1,
      outdatedStacks: 1,
      attentionStacks: 1,
      instanceDriftedStacks: 1,
      digestDriftedStacks: 1,
      lastAuditAt: '2024-01-10T12:00:00Z',
    },
    stacks: [
      {
        id: 'stack-1',
        instanceId: 'instance-1',
        instanceName: 'hml-primary',
        portainerStackId: 101,
        endpointId: 1,
        name: 'xpory-api',
        status: 1,
        type: 1,
        lastSnapshotAt: null,
        outdated: true,
        drifted: false,
        instanceDrifted: true,
        digestDrifted: true,
        removedAt: null,
      },
      {
        id: 'stack-2',
        instanceId: 'instance-1',
        instanceName: 'hml-primary',
        portainerStackId: 102,
        endpointId: 1,
        name: 'xpory-front',
        status: 1,
        type: 1,
        lastSnapshotAt: null,
        outdated: false,
        drifted: false,
        instanceDrifted: false,
        digestDrifted: false,
        removedAt: null,
      },
      {
        id: 'stack-3',
        instanceId: 'instance-1',
        instanceName: 'hml-primary',
        portainerStackId: 103,
        endpointId: 1,
        name: 'xpory-worker',
        status: 0,
        type: 1,
        lastSnapshotAt: null,
        outdated: false,
        drifted: false,
        instanceDrifted: false,
        digestDrifted: false,
        removedAt: null,
      },
    ],
  },
  instances: [
    {
      id: 'instance-1',
      name: 'hml-primary',
      baseUrl: 'https://hml.xpory.local',
      environment: 'hml',
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
  ],
  stacksLocal: [
    {
      id: 'local-1',
      name: 'xpory-api',
      description: 'API principal',
      composeTemplate:
        'version: "3"\nservices:\n  api:\n    image: xpory/api:{{VERSION}}\n    environment:\n      - APP_ALLOWED_ORIGINS={{APP_ALLOWED_ORIGINS}}\n      - DB_HOST_APP={{DB_HOST_APP}}\n      - DB_PASSWORD_APP={{DB_PASSWORD_APP}}\n      - INTEGRATION_CLIENT_SECRET={{INTEGRATION_CLIENT_SECRET}}\n      - APP_ENV={{APP_ENV}}\n      - LOG_LEVEL={{LOG_LEVEL}}\n      - VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES={{VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES}}\n',
      currentVersion: '1.0.0',
      createdAt: '2024-01-10T09:00:00Z',
      updatedAt: '2024-01-10T09:30:00Z',
    },
    {
      id: 'local-2',
      name: 'xpory-front',
      description: 'Frontend',
      composeTemplate: 'version: "3"\nservices:\n  web:\n    image: xpory/front:2.0.0\n',
      currentVersion: '2.0.0',
      createdAt: '2024-01-10T09:05:00Z',
      updatedAt: '2024-01-10T09:35:00Z',
    },
    {
      id: 'local-3',
      name: 'xpory-worker',
      description: 'Worker',
      composeTemplate: 'version: \"3\"\\nservices:\\n  worker:\\n    image: xpory/worker:1.0.0\\n',
      currentVersion: '1.0.0',
      createdAt: '2024-01-10T09:08:00Z',
      updatedAt: '2024-01-10T09:38:00Z',
    },
  ],
  stackLocalVersions: {
    'local-1': [
      {
        id: 'version-1',
        stackId: 'local-1',
        version: '1.0.0',
        description: 'Versao inicial',
        composeTemplate:
          'version: "3"\nservices:\n  api:\n    image: xpory/api:{{VERSION}}\n    environment:\n      - APP_ALLOWED_ORIGINS={{APP_ALLOWED_ORIGINS}}\n      - DB_HOST_APP={{DB_HOST_APP}}\n      - DB_PASSWORD_APP={{DB_PASSWORD_APP}}\n      - INTEGRATION_CLIENT_SECRET={{INTEGRATION_CLIENT_SECRET}}\n      - APP_ENV={{APP_ENV}}\n      - LOG_LEVEL={{LOG_LEVEL}}\n      - VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES={{VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES}}\n',
        createdAt: '2024-01-10T09:00:00Z',
        createdBy: null,
      },
    ],
    'local-2': [
      {
        id: 'version-2',
        stackId: 'local-2',
        version: '2.0.0',
        description: 'Versao atual',
        composeTemplate: 'version: "3"\nservices:\n  web:\n    image: xpory/front:2.0.0\n',
        createdAt: '2024-01-10T09:05:00Z',
        createdBy: null,
      },
    ],
    'local-3': [
      {
        id: 'version-3',
        stackId: 'local-3',
        version: '1.0.0',
        description: 'Versao atual',
        composeTemplate: 'version: "3"\nservices:\n  worker:\n    image: xpory/worker:1.0.0\n',
        createdAt: '2024-01-10T09:08:00Z',
        createdBy: null,
      },
    ],
  },
  stackLocalVariables: {
    'local-1': [
      {
        id: 'var-1',
        stackId: 'local-1',
        variableName: 'APP_ALLOWED_ORIGINS',
        description: 'Lista de origens permitidas para CORS em ambientes com multiplos frontends',
        defaultValue:
          'http://localhost:3001,http://127.0.0.1:3001,https://admin.governance.xpory.com.br',
        isRequired: true,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-2',
        stackId: 'local-1',
        variableName: 'DB_HOST_APP',
        description: 'Host do banco app',
        defaultValue: 'postgres',
        isRequired: true,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-3',
        stackId: 'local-1',
        variableName: 'DB_PASSWORD_APP',
        description: 'Senha do banco app',
        defaultValue: 'super-secret-password-1234567890',
        isRequired: true,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-4',
        stackId: 'local-1',
        variableName: 'INTEGRATION_CLIENT_SECRET',
        description: 'Token de integracao com limite alto de caracteres para validar quebra',
        defaultValue:
          'b5cfdc74e3f94a6bbf37b9f4e0f5c1c2e3f4a5b6c7d8e9f0a1b2c3d4e5f6g7h8',
        isRequired: false,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-7',
        stackId: 'local-1',
        variableName: 'VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES',
        description:
          'Descricao extremamente longa para validar quebra de linha, truncamento e comportamento do layout quando o texto cresce demais na coluna.',
        defaultValue:
          'https://very-long-domain.example.com/path/to/resource/with/a/very/long/query?param=one&param=two&param=three&param=four&param=five',
        isRequired: false,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-5',
        stackId: 'local-1',
        variableName: 'APP_ENV',
        description: 'Ambiente da aplicacao',
        defaultValue: 'production',
        isRequired: true,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
      {
        id: 'var-6',
        stackId: 'local-1',
        variableName: 'LOG_LEVEL',
        description: 'Nivel de log',
        defaultValue: 'info',
        isRequired: false,
        createdAt: '2024-01-10T09:10:00Z',
        updatedAt: '2024-01-10T09:10:00Z',
      },
    ],
  },
  stackInstanceVariables: {
    'local-1': {
      'instance-1': [
        {
          stackId: 'local-1',
          instanceId: 'instance-1',
          variableName: 'APP_ALLOWED_ORIGINS',
          value: 'http://localhost:3001,http://127.0.0.1:3001',
          createdAt: '2024-01-10T10:10:00Z',
          updatedAt: '2024-01-10T10:10:00Z',
        },
        {
          stackId: 'local-1',
          instanceId: 'instance-1',
          variableName: 'INTEGRATION_CLIENT_SECRET',
          value: 'c5e1f7a2b9d345671234567890abcdefabcdefabcdefabcdefabcdefabcdef',
          createdAt: '2024-01-10T10:10:00Z',
          updatedAt: '2024-01-10T10:10:00Z',
        },
        {
          stackId: 'local-1',
          instanceId: 'instance-1',
          variableName: 'VERY_LONG_VARIABLE_NAME_TO_FORCE_LAYOUT_BREAK_AND_TEST_WRAP_RULES',
          value:
            'value-with-very-long-content-to-test-input-overflow-and-ellipsis-without-breaking-the-table-layout-1234567890',
          createdAt: '2024-01-10T10:10:00Z',
          updatedAt: '2024-01-10T10:10:00Z',
        },
      ],
    },
  },
  portainer: {
    endpoints: [
      {
        id: 1,
        name: 'primary',
      },
    ],
  },
  audit: {
    resultsByStack: {
      'stack-1': [
        {
          id: 'audit-1',
          stackUuid: 'stack-1',
          stackName: 'xpory-api',
          instanceName: 'hml-primary',
          image: 'xpory/api',
          currentTag: '1.0.0',
          latestTag: '1.1.0',
          updateAvailable: true,
          riskLevel: 'medio',
          createdAt: '2024-01-10T12:30:00Z',
        },
        {
          id: 'audit-2',
          stackUuid: 'stack-1',
          stackName: 'xpory-api',
          instanceName: 'hml-primary',
          image: 'xpory/worker',
          currentTag: '2.0.0',
          latestTag: '2.0.0',
          updateAvailable: false,
          riskLevel: 'ok',
          createdAt: '2024-01-10T12:30:00Z',
        },
      ],
      'stack-2': [],
    },
    resultsAll: [
      {
        id: 'audit-3',
        stackUuid: 'stack-1',
        stackName: 'xpory-api',
        instanceName: 'hml-primary',
        endpointId: 1,
        image: 'xpory/api',
        currentTag: '1.0.0',
        latestTag: '1.1.0',
        updateAvailable: true,
        riskLevel: 'alto',
        createdAt: '2024-01-10T12:30:00Z',
      },
      {
        id: 'audit-4',
        stackUuid: 'stack-2',
        stackName: 'xpory-front',
        instanceName: 'hml-primary',
        endpointId: 1,
        image: 'xpory/front',
        currentTag: '2.0.0',
        latestTag: '2.0.0',
        updateAvailable: false,
        riskLevel: 'ok',
        createdAt: '2024-01-10T12:35:00Z',
      },
    ],
  },
  registry: {
    imagesByStack: {
      'stack-1': [
        {
          stackId: 'stack-1',
          instanceId: 'instance-1',
          image: 'xpory/api',
          tag: '1.0.0',
          digest: 'sha256:111',
          registryDigest: 'sha256:222',
          drifted: true,
          lastSeenAt: '2024-01-10T12:00:00Z',
        },
      ],
    },
  },
  notifications: {
    logs: [
      {
        id: 'log-1',
        channel: 'email',
        recipient: 'ops@xpory.com',
        subject: 'Stack xpory-api',
        message: 'Notificacao enviada.',
        status: 'sent',
        providerResponse: null,
        createdAt: '2024-01-10T09:00:00Z',
      },
      {
        id: 'log-2',
        channel: 'sms',
        recipient: '+5511999999999',
        subject: 'Stack xpory-front',
        message: 'Falha no envio.',
        status: 'failed',
        providerResponse: null,
        createdAt: '2024-01-10T09:30:00Z',
      },
      {
        id: 'log-3',
        channel: 'sms',
        recipient: '+5511888888888',
        subject: 'Stack xpory-api',
        message: 'Mensagem em fila.',
        status: 'queued',
        providerResponse: null,
        createdAt: '2024-01-10T10:00:00Z',
      },
    ],
  },
  update: {
    compose: 'version: "3"\nservices:\n  api:\n    image: xpory/api:1.0.0\n',
    steps: {
      preHealth: true,
      postHealth: true,
    },
  },
} as const;
